### ISSUE TITLE
Is product list pop-up under table_order hyerarc?

### ISSUE THREAD

**Issue by Vikirito1** [Vikirito1/Quiosque#42]
Product pop-up must be created as another screen or it will be under table_order?

(E.g:
module > home - splash - table_order - **popup_menu**
or
modules > table_order > widget - **popup_menu**).

**Comment by Vikirito1** [comment]
I have noticed that popup menu is an widget so it is not another screen.

**Comment by Vikirito1** [comment]
But I think we should creat a class

**Comment by bmsrangel** [comment]
Considering the context, I believe our first approach should be the popup option.

So, you are partially correct. In order to show a popup window, we must use the showDialog function. However, it needs a dialog, which can be a StatelessWidget returning an AlertDialog (it has already a "scaffold" we can use, instead of creating a popup from scratch).
