### ISSUE TITLE
an error occurr when opens a closed table, add item

### ISSUE THREAD

**Issue by Vikirito1** [Vikirito1/Quiosque#58]
![image](https://user-images.githubusercontent.com/91020833/145699163-704fc703-9a43-4617-8559-b19929c50837.png)

The error in the picture occurrs when open the table >> add an item >> change quantity.

If this steps are performed  is possible to replicate errors.

By what I've checked it is because the orderId passed to the table_order_page was null (table was closed).

Some solutions would be remove the null check (!) from DTO or passing the orderID to the data.orderId when opening the table.

**Comment by bmsrangel** [comment]
Actually, we're getting this orderId from the variable "data", which contains information sent by the previous screen (the table list).

When we open a new order, indeed "data.orderId" is null.

However, since we started using the store containing the orderId variable, we should no longer use "data.orderId" for anything else but pass the "orderId" to the store.

Bottom of line, replacr "data.orderId!" by "orderProductsStore.orderId!"

**Comment by Vikirito1** [comment]
Sure, I agree no longer use "data.something".

**Comment by bmsrangel** [comment]
Closed by PR #60
